### ISSUE TITLE
魅族Pro5升级Flyme6后ShadowSocks找不到kcptun插件

### ISSUE THREAD

**Issue by iLibra** [shadowsocks/kcptun-android#23]
之前Pro5在Flyme5上运行kcptun插件一切正常。升级6后每次都找不到插件了。

具体log请见如下

> 09-25 10:32:59.001 2818-2906/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.shadowsocks/.MainActivity bnds=[24,384][282,672]} from uid 10013 on display 0 from pid 3832
09-25 10:32:59.021 3832-9012/? I/Launcher.MD5: createMD5, pathFile is /data/app/com.github.shadowsocks-2/base.apk
09-25 10:32:59.041 15387-15411/? W/GooglePlayServicesUtil: Google Play Store is missing.
09-25 10:32:59.051 15387-15411/? W/GooglePlayServicesUtil: Google Play Store is missing.
09-25 10:32:59.701 2818-2955/? E/WifiStateMachine: mLastSignalLevel:3, newSignalLevel:3
09-25 10:33:00.041 3031-3031/? W/recents.Component: create a new LoadPlan to load thumbnail -- background
09-25 10:33:00.061 3031-3031/? W/recents.Performance: preload while task Change spend : 22
09-25 10:33:02.711 2818-2955/? E/WifiStateMachine: mLastSignalLevel:3, newSignalLevel:3
09-25 10:33:04.381 2383-2383/? I/audio_hw_primary: adev_set_parameters(): kvpairs = mediaserver_monitor=1
09-25 10:33:04.501 2818-2906/? W/Interception: isInterceptByRule realCallingPid: 15413 isInterceptAsUsual: true isMatch: false, runType===provider|||callerPkg===com.github.shadowsocks|||calleePkg===com.github.shadowsocks.plugin.kcptun|||calleeClass===com.github.shadowsocks.plugin.kcptun.BinaryProvider|||processName===com.github.shadowsocks.plugin.kcptun|||action===*|||data===*|||extras===Bundle[{uri=com.github.shadowsocks.plugin.kcptun.BinaryProvider}]|||interception===false
09-25 10:33:04.501 15413-7892/? E/ActivityThread: Failed to find provider info for com.github.shadowsocks.plugin.kcptun.BinaryProvider
09-25 10:33:04.501 15413-7892/? W/System.err: java.lang.IllegalArgumentException: Unknown URI content://com.github.shadowsocks.plugin.kcptun.BinaryProvider
09-25 10:33:04.501 15413-7892/? W/System.err:     at android.content.ContentResolver.call(ContentResolver.java:1379)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.plugin.PluginManager$.initNativeFast(PluginManager.scala:135)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.plugin.PluginManager$.initNative(PluginManager.scala:124)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.plugin.PluginManager$.init(PluginManager.scala:97)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$class.connect(BaseService.scala:156)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.ShadowsocksVpnService.connect(ShadowsocksVpnService.scala:117)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$$anonfun$onStartCommand$1.apply$mcV$sp(BaseService.scala:283)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$$anonfun$onStartCommand$1.apply(BaseService.scala:283)
09-25 10:33:04.501 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$$anonfun$onStartCommand$1.apply(BaseService.scala:283)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
09-25 10:33:04.501 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
09-25 10:33:04.501 15413-7892/? W/PluginManager: Initializing native plugin fast mode failed. Falling back to slow mode.
09-25 10:33:04.501 2818-2837/? W/Interception: isInterceptByRule realCallingPid: 15413 isInterceptAsUsual: true isMatch: false, runType===provider|||callerPkg===com.github.shadowsocks|||calleePkg===com.github.shadowsocks.plugin.kcptun|||calleeClass===com.github.shadowsocks.plugin.kcptun.BinaryProvider|||processName===com.github.shadowsocks.plugin.kcptun|||action===*|||data===*|||extras===Bundle[{uri=com.github.shadowsocks.plugin.kcptun.BinaryProvider}]|||interception===false
09-25 10:33:04.501 15413-7892/? E/ActivityThread: Failed to find provider info for com.github.shadowsocks.plugin.kcptun.BinaryProvider
09-25 10:33:04.521 15413-7892/? W/System.err: java.io.FileNotFoundException: 未知插件 kcptun
09-25 10:33:04.521 15413-7892/? W/System.err:     at com.github.shadowsocks.plugin.PluginManager$.init(PluginManager.scala:108)
09-25 10:33:04.521 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$class.connect(BaseService.scala:156)
09-25 10:33:04.521 15413-7892/? W/System.err:     at com.github.shadowsocks.ShadowsocksVpnService.connect(ShadowsocksVpnService.scala:117)
09-25 10:33:04.521 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$$anonfun$onStartCommand$1.apply$mcV$sp(BaseService.scala:283)
09-25 10:33:04.521 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$$anonfun$onStartCommand$1.apply(BaseService.scala:283)
09-25 10:33:04.521 15413-7892/? W/System.err:     at com.github.shadowsocks.BaseService$$anonfun$onStartCommand$1.apply(BaseService.scala:283)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
09-25 10:33:04.521 15413-7892/? W/System.err:     at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
09-25 10:33:04.561 3031-3031/? I/PhoneStatusBar: updateNotificationCountChange,mLastHasNotification:true , hasActiveNotifications:true
09-25 10:33:04.561 3031-3031/? W/StatusBar: removeFakeNotificationViews()---removeNotification for unknown pkg: com.github.shadowsocks
09-25 10:33:04.561 3031-3031/? I/PhoneStatusBar: updateNotificationCountChange,mLastHasNotification:true , hasActiveNotifications:true
09-25 10:33:04.581 15387-15387/? E/ShadowsocksMainActivity: Error to start VPN service: 无法连接远程服务器: 未知插件 kcptun
09-25 10:33:05.471 3587-3587/? W/System.err: org.json.JSONException: Value a.mlinks.cc of type java.lang.String cannot be converted to JSONObject
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.tencent.smtt.net.SWOfflineFramework$3.run(Unknown Source)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5574)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-25 10:33:05.471 3587-3587/? W/System.err: org.json.JSONException: Value servicewechat.com of type java.lang.String cannot be converted to JSONObject
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.tencent.smtt.net.SWOfflineFramework$3.run(Unknown Source)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5574)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-25 10:33:05.471 3587-3587/? W/System.err: org.json.JSONException: Value m.sogou.com of type java.lang.String cannot be converted to JSONObject
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.tencent.smtt.net.SWOfflineFramework$3.run(Unknown Source)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5574)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-25 10:33:05.471 3587-3587/? W/System.err: org.json.JSONException: Value m.baidu.com of type java.lang.String cannot be converted to JSONObject
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSON.typeMismatch(JSON.java:111)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:160)
09-25 10:33:05.471 3587-3587/? W/System.err:     at org.json.JSONObject.<init>(JSONObject.java:173)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.tencent.smtt.net.SWOfflineFramework$3.run(Unknown Source)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
09-25 10:33:05.471 3587-3587/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5574)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-25 10:33:05.471 3587-3587/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:962)
09-25 10:33:05.471 3587-3587/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
09-25 10:33:05.721 2818-2955/? E/WifiStateMachine: mLastSignalLevel:3, newSignalLevel:3
09-25 10:33:08.731 2818-2955/? E/WifiStateMachine: mLastSignalLevel:3, newSignalLevel:3
09-25 10:33:10.131 2818-2942/? I/WindowManager: interceptKeyTq keycode=26 interactive=true keyguardActive=false policyFlags=22000000 down =true canceled = false isWakeKey=false mVolumeDownKeyTriggered =false mVolumeUpKeyTriggered =false result = 1 useHapticFeedback = false isInjected = false result = 1
09-25 10:33:10.341 2818-2942/? I/WindowManager: interceptKeyTq keycode=26 interactive=true keyguardActive=false policyFlags=22000000 down =false canceled = false isWakeKey=false mVolumeDownKeyTriggered =false mVolumeUpKeyTriggered =false result = 1 useHapticFeedback = false isInjected = false result = 1
09-25 10:33:10.341 2818-2942/? I/PowerManagerService: Going to sleep due to power button (uid 1000)...
09-25 10:33:10.341 2818-2818/? I/MzFingerManager:  notifyScreenOff--------  39698973
09-25 10:33:10.341 2818-2916/? I/PowerManagerService: Sleeping (uid 1000)...
09-25 10:33:10.351 3742-3742/? I/fpc_hal: _fpc_hal_click_stop - FPC EVENT Aborting HAL before Joining with click thread: 2228196096
                                          ;985
09-25 10:33:10.351 3742-3742/? I/fpc_hal: fpc_hal_abort, _fpc_hal_abort is 1;988
09-25 10:33:10.351 3742-3742/? I/fpc_hal: fpc_hal_abort, _fpc_hal_abort is 1;772
09-25 10:33:10.351 3742-3742/? I/fpc_hal: fpc_hal_abort, send signal _fpc_hal_irq_sem;776
09-25 10:33:10.351 3742-3742/? I/fpc_hal: _fpc_hal_click_stop - FPC EVENT Joining with click thread: 2228196096
                                          ;998
09-25 10:33:10.351 3742-8197/? I/fpc_hal: fpc_hal_wait_for_finger_present_click prepare spi;219
09-25 10:33:10.351 3742-8197/? I/fpc_hal: _fpc_hal_click_thread - FPC EVENT - finger present not detected continuing loop;841
09-25 10:33:10.351 3742-3742/? I/fpc_hal: fpc_hal_spi_prepare: spi already prepare;607
09-25 10:33:10.351 3742-3742/? I/fpc_hal: fpc_hal_notify_app_action prepare spi with click stop;668
09-25 10:33:10.351 3742-3742/? I/fpc_tac: -->fpc_tac_deep_sleep;949
09-25 10:33:10.351 3031-3031/? I/PhoneStatusBar: updateNotificationCountChange,mLastHasNotification:true , hasActiveNotifications:true
09-25 10:33:10.361 3742-3742/? I/fpc_tac: <--fpc_tac_deep_sleep return 0;958
09-25 10:33:10.361 3742-3742/? I/fpc_tac: fpc_tac_deep_sleep unprepare spi;960
09-25 10:33:10.361 3031-3031/? I/PalmRejection: disableProximityLockLocked, mProximitySensorEnabled = false
09-25 10:33:10.361 3031-3031/? I/PalmRejection: disableProximityLockLocked() failed... Proximity Sensor already disabled
09-25 10:33:10.361 3031-3031/? I/PhoneStatusBar: updateNotificationCountChange,mLastHasNotification:true , hasActiveNotifications:true
09-25 10:33:10.371 3305-3557/? I/BatteryConsumeMonitor: watting idle mode !
09-25 10:33:10.371 2818-2818/? I/MzPowerStateMachine: power state machine receive action: android.intent.action.SCREEN_OFF
09-25 10:33:10.371 2818-2818/? I/MzPowerStateMachine: ACTION_SCREEN_OFF
09-25 10:33:10.381 2383-2383/? I/audio_hw_primary: adev_set_parameters(): kvpairs = screen_state=off
09-25 10:33:10.381 2818-2955/? E/WifiStateMachine: cancelDelayedScan -> 275
09-25 10:33:10.381 2818-2955/? E/native: do suspend true
09-25 10:33:10.411 3031-3031/? I/MeizuKeyguardThemeManager: setBarState ------ statusBarState=1,keyguardFadingAway=false,goingToFullShade=false,keyguardShowing=true
09-25 10:33:10.411 3031-3031/? I/MeizuKeyguardThemeManager: setBarState 1
09-25 10:33:10.421 3031-3031/? I/PhoneStatusBar: updateNotificationCountChange,mLastHasNotification:true , hasActiveNotifications:false
09-25 10:33:10.431 4338-4981/? W/System.err: java.io.FileNotFoundException: /sys/module/lowmemorykiller/parameters/adj: open failed: EACCES (Permission denied)
09-25 10:33:10.431 4338-4981/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:472)
09-25 10:33:10.431 4338-4981/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:76)
09-25 10:33:10.431 4338-4981/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:103)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tmsdk.common.internal.utils.i.dQ(SourceFile:1299)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.akz.qE(SourceFile:133)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.akz.Tt(SourceFile:72)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.akz.Ts(SourceFile:31)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.ajf.b(SourceFile:581)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.ajf.DR(SourceFile:391)
09-25 10:33:10.431 4338-4981/? W/System.err:     at com.tencent.qqpimsecure.plugin.processmanager.bg.PiProcessManagerUD$1.a(SourceFile:103)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.cd$5.run(SourceFile:349)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.aet.d(SourceFile:375)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.aet.c(SourceFile:360)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.aet.TM(SourceFile:159)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.aev.a(SourceFile:57)
09-25 10:33:10.431 4338-4981/? W/System.err:     at tcs.aet$1.run(SourceFile:227)
09-25 10:33:10.431 4338-4981/? W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
09-25 10:33:10.431 4338-4981/? W/System.err:     at libcore.io.Posix.open(Native Method)
09-25 10:33:10.431 4338-4981/? W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
09-25 10:33:10.431 4338-4981/? W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:453)
09-25 10:33:10.431 4338-4981/? W/System.err: 	... 15 more
09-25 10:33:10.451 3031-3031/? I/ChargeViewUtils: onRefreshBatteryInfo

**Comment by iLibra** [comment]
从@ChaoJohn的回答中，找到解决办法了

> Flyme6

Reason: kcptun plugin could not be wake up by shadowsocks due to the system limitation.

Solution: Security -> Permissions -> Run in background -> find 'kcptun' -> choose 'Keep running in background' instead of 'Smart Background(recommended)' which is the default.

The Security is a flyme build-in app which has a green circle icon with a white umbrella in it.

Hope it will help you guys :)
