### ISSUE TITLE
可以在lineagesOS上跑，不能在flyme6上跑

### ISSUE THREAD

**Issue by mountainguan** [shadowsocks/kcptun-android#4]
一样的配置，在lineagesOS上可以运行。在flyme6上提示Unknown plugin kcptun....而我已经安装过了kcpun的插件了。不清楚怎么抓这个app的log，所以不能附上

**Comment by Mygod** [comment]
Logcat please. (`adb logcat | grep shadowsocks`)

**Comment by mountainguan** [comment]
这是魅族基于安卓5.1.1的Flyme6系统上的logcat
![image](http://p1.bpimg.com/4851/af4613d83015e806.jpg)

**Comment by Mygod** [comment]
Try disabling xposed, privacy protection apps, etc.

**Comment by mountainguan** [comment]
关闭xposed以后，少了xposed的错误日志。但是kcptun还是用不了,这是新的日志
![image](http://i1.piimg.com/567571/3890fae4c4c5102d.jpg)

**Comment by mountainguan** [comment]
![image](http://p1.bqimg.com/1949/3890fae4c4c5102d.jpg)

**Comment by Mygod** [comment]
Please try 4d3fab233b026b4aa2b496693e444ad3f6bec524. @madeye

**Comment by Mygod** [comment]
@madeye Could you please kindly build a nightly? Thanks!

**Comment by madeye** [comment]
OK. https://github.com/shadowsocks/kcptun-android/releases/tag/v0.0.3

**Comment by Mygod** [comment]
Closing this due to inactivity. But I'm going to keep this new authority anyway.

**Comment by Dreista** [comment]
Happened to get a Meizu device. Hope the imformation provided below may help.

Device: Meizu Meilan Note 2 China Telecom Edition (M571C)
Android Version: 5.1
Flyme Version: 5.1.9.0Q

Shadowsocks-Android Version: 4.1.1
Kcptun-Android Version: 0.0.4

Log:
I/ActivityManager(  833): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.github.shadowsocks/.MainActivity bnds=[48,96][294,384]} from uid 10086 on display 0 from pid 1776
I/System.out( 1776): createMD5, pathFile is /data/app/com.github.shadowsocks-1/base.apk
I/ActivityManager(  833): Start proc 6319:com.github.shadowsocks/u0a122 for activity com.github.shadowsocks/.MainActivity
I/ActivityManager(  833): Start proc 6347:com.github.shadowsocks:bg/u0a122 for service com.github.shadowsocks/com.evernote.android.job.JobRescheduleService
I/WindowManager(  833): Gaining focus: Window{12f3039e u0 com.github.shadowsocks/com.github.shadowsocks.MainActivity}
I/ActivityManager(  833): [AppLaunch] Displayed Displayed com.github.shadowsocks/.MainActivity: +1s351ms
I/Vpn     (  833): prepare old:com.github.shadowsocks,new:null
I/Vpn     (  833): prepare old:com.github.shadowsocks,new:null
W/Interception(  833): isInterceptByRule realCallingPid: 6347 isInterceptAsUsual: true isMatch: false, runType===provider|||callerPkg===com.github.shadowsocks|||calleePkg===com.github.shadowsocks.plugin.kcptun|||calleeClass===com.github.shadowsocks.plugin.kcptun.BinaryProvider|||processName===com.github.shadowsocks.plugin.kcptun|||action===*|||data===*|||extras===Bundle[{uri=com.github.shadowsocks.plugin.kcptun.BinaryProvider}]|||interception===false
E/ActivityThread( 6347): Failed to find provider info for com.github.shadowsocks.plugin.kcptun.BinaryProvider
W/System.err( 6347): java.lang.IllegalArgumentException: Unknown URI content://com.github.shadowsocks.plugin.kcptun.BinaryProvider
W/System.err( 6347): 	at com.github.shadowsocks.plugin.PluginManager$.initNativeFast(PluginManager.scala:135)
W/System.err( 6347): 	at com.github.shadowsocks.plugin.PluginManager$.initNative(PluginManager.scala:124)
W/System.err( 6347): 	at com.github.shadowsocks.plugin.PluginManager$.init(PluginManager.scala:97)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$class.connect(BaseService.scala:162)
W/System.err( 6347): 	at com.github.shadowsocks.ShadowsocksVpnService.connect(ShadowsocksVpnService.scala:121)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply$mcV$sp(BaseService.scala:186)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply(BaseService.scala:186)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply(BaseService.scala:186)
W/Interception(  833): isInterceptByRule realCallingPid: 6347 isInterceptAsUsual: true isMatch: false, runType===provider|||callerPkg===com.github.shadowsocks|||calleePkg===com.github.shadowsocks.plugin.kcptun|||calleeClass===com.github.shadowsocks.plugin.kcptun.BinaryProvider|||processName===com.github.shadowsocks.plugin.kcptun|||action===*|||data===*|||extras===Bundle[{uri=com.github.shadowsocks.plugin.kcptun.BinaryProvider}]|||interception===false
E/ActivityThread( 6347): Failed to find provider info for com.github.shadowsocks.plugin.kcptun.BinaryProvider
W/System.err( 6347): 	at com.github.shadowsocks.plugin.PluginManager$.init(PluginManager.scala:108)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$class.connect(BaseService.scala:162)
W/System.err( 6347): 	at com.github.shadowsocks.ShadowsocksVpnService.connect(ShadowsocksVpnService.scala:121)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply$mcV$sp(BaseService.scala:186)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply(BaseService.scala:186)
W/System.err( 6347): 	at com.github.shadowsocks.BaseService$$anonfun$startRunner$1.apply(BaseService.scala:186)

**Comment by ChaosJohn** [comment]
Flyme6

Reason: kcptun plugin could not be wake up by shadowsocks due to the system limitation. 

Solution: Security -> Permissions -> Run in background -> find 'kcptun' -> choose 'Keep running in background' instead of 'Smart Background(recommended)' which is the default. 

The Security is a flyme build-in app which has a green circle icon with a white umbrella in it. 

Hope it will help you guys :)

**Comment by yudenzel** [comment]
@ChaosJohn 

Thanks for your detail help!

It finally works!
